name: testebippstartup
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  dio: ^3.0.10
  dio_http_cache: ^0.2.7

dev_dependencies:
  mobx_codegen: ^1.0.3
  build_runner: ^1.9.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

   # To add assets to your application, add an assets section, like this:
  assets:
       - assets/images/bg-home.png
       - assets/images/img1.jpg
       - assets/images/img2.jpg
       - assets/database/database.json
       - assets/images/main_icon.png
       - assets/images/menu.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
